def hn
    $f.push("")
end

def cm(comment, close = false)
    a = close ? "/" : ""
    temp = "<!-- #{a}#{comment} -->"
    $f.push(temp)
end

def genContent(f, filePath)
  content = getFileLines(filePath)
  ignore = false

  id = shrinkFilePathForID(filePath)

  #Three tildes anywhere in the content text file will set the content file as ignored.
  temp = content.index { |x| x.start_with?("~~~") }
  if temp != nil
    ignore = true
  end

  if !ignore
    #The ! marks a section for color/theme
    temp = content.index { |x| x.start_with?("!") }
    theme = nil
    if temp != nil
      theme = content[temp]
      theme = theme[1...theme.length]
      content.delete_at(temp)
    else
      theme = ""
    end

    #The @ marks the header/title of the content box
    temp = content.index { |x| x.start_with?("@") }
    header = nil
    if temp != nil
      header = content[temp]
      header = header[1...header.length]
      content.delete_at(temp)
    end

    #The # marks the subheader/subtitle of the content box
    temp = content.index { |x| x.start_with?("#") }
    subheader = nil
    if temp != nil
      subheader = content[temp]
      subheader = subheader[1...subheader.length]
      content.delete_at(temp)
    end

    #The $ marks the footer of the content box
    temp = content.index { |x| x.start_with?("$") }
    footer = nil
    if temp != nil
      footer = content[temp]
      footer = footer[1...footer.length]
      content.delete_at(temp)
    end

    #The * marks links. It follows this format:
    #*a|b|c|d
    #Where a is the unique number located in the body text, b is the text to replace that number, c is the link, and d is the target
    #d is optional
    #example: *0|my GitHub page|https://github.com/jauq|_blank
    #This would replace *0 in the body text with the text "my GitHub Page" with that link as the link.
    loop do
      temp = content.index { |x| x.start_with?("*") }
      if temp != nil
        link = content[temp]
        content.delete_at(temp)
        link = link.split("|")
        linkTheme = ""
        if theme != nil
          linkTheme = theme
        end
        save = link[3] != nil ? link[3] : "_self"
        content.each do |line|
          line.gsub!(link[0], "<a class=\"#{linkTheme}\" href=\"#{link[2]}\" target=\"#{save}\">#{link[1]}</a>")
        end
      else
        break
      end
    end

    #The % marks pictures. It follows this format:
    #*a|b|c|d
    #Where a is the unique number located in the body text, b is the link to the image, c is alt text, and d is the link
    #d is optional
    #example: %0|/Jauq.github.io/img/bord.jpg|The bord
    #This would replace %0 in the body text with that image.
    loop do
      temp = content.index { |x| x.start_with?("%") }
      if temp != nil
        pic = content[temp]
        content.delete_at(temp)
        pic = pic.split("|")
        content.each do |line|
          if pic.count == 3
            line.gsub!(pic[0], "</p><img src=\"#{pic[1]}\" class=\"img-fluid\" alt=\"#{pic[2]}\"><p class=\"noMargin\">")
          elsif pic.count == 4
            line.gsub!(pic[0], "<a href=\"#{pic[3]}\"></p><img src=\"#{pic[1]}\" alt=\"#{pic[2]}\"><p class=\"noMargin\"></a>")
          end
        end
      else
        break
      end
    end

    #This is the body text. It will add breaks in between lines in the text document, unless from wrapping.
    temp = content.count
    fill = ""
    if temp > 0
      fill = content.join("<br/>")
    end

    f.push("<!-- generated by genContent() in htmlContent.rb -->")
    f.push("<div class=\"row\" id=\"#{id}\">")
    f.push("  <div class=\"col\">")
    f.push("    <div class=\"bodyBox #{theme}\">")
    if header != nil
      f.push("      <h1>#{header}</h1>")
    end
    if subheader != nil
      f.push("      <h2>#{subheader}</h2>")
    end
    if fill != ""
      f.push("      <p class=\"noMargin\">#{fill}</p>")
    end
    if footer != nil
      f.push("      <p class=\"noMargin cancel\"><br/>#{footer}</p>")
    end
    f.push("    </div>")
    f.push("  </div>")
    f.push("</div>")
    f.push("<!-- /generated by genContent() in htmlContent.rb -->")
  end
end

#Incomplete, most likely wont be used for a while.
#A variation of genContent() which creates a different kind of content box.
#It is thinner and has a required thumbnail. The issue with it is that its more work and I have an already capable method.
#I will leave this one active, but unused.

def genMediaContent(f, filePath, genreFilter = nil)
  content = getFileLines(filePath)
  ignore = false

  temp = content.index { |x| x.start_with?("~~~") }
  if temp != nil
    ignore = true
  end

  if !ignore
    temp = content.index { |x| x.start_with?("!") }
    theme = "nHome"
    if temp != nil
      theme = content[temp]
      theme = theme[1...theme.length]
      content.delete_at(temp)
    end

    temp = content.index { |x| x.start_with?("@") }
    title = "Default Title"
    if temp != nil
      title = content[temp]
      title = title[1...title.length]
      content.delete_at(temp)
    end

    temp = content.index { |x| x.start_with?("#") }
    fill = "Default Body Text."
    if temp != nil
      fill = content[temp]
      fill = fill[1...fill.length]
      content.delete_at(temp)
    end

    temp = content.index { |x| x.start_with?("$") }
    genres = []
    if temp != nil
      genres = content[temp]
      genres = genres[1...genres.length].split('|')
      content.delete_at(temp)
    end

    temp = content.index { |x| x.start_with?("%") }
    pic = "/Jauq.github.io/img/256x128pi.jpg"
    if temp != nil
      pic = content[temp]
      pic = pic[1...pic.length]
      content.delete_at(temp)
    end

    page = "/Jauq.github.io/views/" + theme[1...theme.length].downcase + "/" + title + ".html"

    continue = false
    if genreFilter != nil
      if genres.include?(genreFilter)
        continue = true
      end
    else
      continue = true
    end

    if continue
      f.push("<!-- generated by genMediaContent() in htmlContent.rb -->")
      f.push("<div class=\"row\">")
      f.push("  <div class=\"col\">")
      f.push("    <div class=\"mediaBox #{theme} row\">")
      f.push("      <a href=\"#{page}\" class=\"col col-auto\"><img src=\"#{pic}\" alt=\"#{title} Thumbnail\"></img></a>")
      f.push("      <div class=\"mediaContent col-sm-12 col-md\">")
      f.push("        <h1><a class=\"#{theme}\" href=\"#{page}\">#{title}</a></h1>")
      f.push("        <p class=\"noMargin\">#{fill}</p>")
      if genres != []
        f.push("        <br class=\"showMed\"/>")
        f.push("        <div class=\"genreTags\">")
        genres.each do |genre|
          f.push("          <a class=\"#{theme}\" href=\"/Jauq.github.io/views/games/genres/#{genre.downcase}.html\">#{genre}</a>")
        end
        f.push("        </div>")
      end
      f.push("      </div>")
      f.push("    </div>")
      f.push("  </div>")
      f.push("</div>")
      f.push("<!-- /generated by genMediaContent() in htmlContent.rb -->")
    end
  end
end
